giger-postgres:
    image: 'postgres:11.4'
    restart: always
    container_name: 'giger-postgres'
    environment:
      - POSTGRES_ROOT_PASSWORD=example
      - POSTGRES_DB=giger_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
